version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: SpringBootTest
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  inventoryManagement:
    build: ./inventoryManagement
    image: yusufadisaputro-inventorymanagement
    ports:
      - 8080:8080
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SpringBootTest?useSSL=false
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  customerManagement:
    build: ./customerManagement
    image: yusufadisaputro-customermanagement
    ports:
      - 8081:8080
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SpringBootTest?useSSL=false
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  salesOrderManagement:
    build: ./salesOrderManagement
    image: yusufadisaputro-salesordermanagement
    ports:
      - 8082:8080
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SpringBootTest?useSSL=false
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  db_data:
